"""initial data model

Revision ID: 82f09410d515
Revises: 
Create Date: 2026-07-02 12:11:55.791927

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82f09410d515'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module', sa.Enum('pronunciation', 'drill', name='content_module', native_enum=False, length=32), nullable=False),
    sa.Column('sector', sa.Enum('kaigo', 'food_manufacturing', 'restaurant', 'general', name='sector', native_enum=False, length=32), nullable=False),
    sa.Column('text_ja', sa.Text(), nullable=False),
    sa.Column('furigana', sa.Text(), nullable=True),
    sa.Column('gloss_id', sa.Text(), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_items'))
    )
    op.create_index(op.f('ix_content_items_module'), 'content_items', ['module'], unique=False)
    op.create_index(op.f('ix_content_items_sector'), 'content_items', ['sector'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.Enum('lpk', 'company', name='org_type', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_table('quiz_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section', sa.Enum('grammar', 'vocabulary', 'reading', 'listening', name='quiz_section', native_enum=False, length=32), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('choices', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('answer_index', sa.Integer(), nullable=False),
    sa.Column('explanation_id', sa.Text(), nullable=True),
    sa.Column('review_flag', sa.Boolean(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_items'))
    )
    op.create_index(op.f('ix_quiz_items_section'), 'quiz_items', ['section'], unique=False)
    op.create_table('cohorts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sector', sa.Enum('kaigo', 'food_manufacturing', 'restaurant', 'general', name='sector', native_enum=False, length=32), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_cohorts_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cohorts'))
    )
    op.create_index(op.f('ix_cohorts_org_id'), 'cohorts', ['org_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('student', 'teacher', 'admin', name='user_role', native_enum=False, length=32), nullable=False),
    sa.Column('locale', sa.Enum('id', 'ja', name='locale', native_enum=False, length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_users_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('daily', 'monthly', name='attendance_kind', native_enum=False, length=32), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('value >= 0 AND value <= 100', name=op.f('ck_attendance_records_value_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_attendance_records_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_records')),
    sa.UniqueConstraint('user_id', 'kind', 'record_date', name=op.f('uq_attendance_records_user_id'))
    )
    op.create_index(op.f('ix_attendance_records_user_id'), 'attendance_records', ['user_id'], unique=False)
    op.create_table('attitude_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_attitude_reviews_reviewer_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_attitude_reviews_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attitude_reviews'))
    )
    op.create_index(op.f('ix_attitude_reviews_user_id'), 'attitude_reviews', ['user_id'], unique=False)
    op.create_table('conversation_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scenario', sa.String(length=64), nullable=False),
    sa.Column('sector', sa.Enum('kaigo', 'food_manufacturing', 'restaurant', 'general', name='sector', native_enum=False, length=32), nullable=False),
    sa.Column('mode', sa.Enum('text', 'voice', name='session_mode', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'abandoned', name='session_status', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversation_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_sessions'))
    )
    op.create_index(op.f('ix_conversation_sessions_user_id'), 'conversation_sessions', ['user_id'], unique=False)
    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cohort_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], name=op.f('fk_enrollments_cohort_id_cohorts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_enrollments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollments')),
    sa.UniqueConstraint('cohort_id', 'user_id', name=op.f('uq_enrollments_cohort_id'))
    )
    op.create_index(op.f('ix_enrollments_cohort_id'), 'enrollments', ['cohort_id'], unique=False)
    op.create_index(op.f('ix_enrollments_user_id'), 'enrollments', ['user_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_events_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index(op.f('ix_events_type'), 'events', ['type'], unique=False)
    op.create_index('ix_events_user_created', 'events', ['user_id', 'created_at'], unique=False)
    op.create_table('interview_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scenario', sa.String(length=64), nullable=False),
    sa.Column('sector', sa.Enum('kaigo', 'food_manufacturing', 'restaurant', 'general', name='sector', native_enum=False, length=32), nullable=False),
    sa.Column('mode', sa.Enum('text', 'voice', name='session_mode', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'abandoned', name='session_status', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_interview_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_sessions'))
    )
    op.create_index(op.f('ix_interview_sessions_user_id'), 'interview_sessions', ['user_id'], unique=False)
    op.create_table('mock_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('num_questions', sa.Integer(), nullable=False),
    sa.Column('num_correct', sa.Integer(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score >= 0 AND score <= 100', name=op.f('ck_mock_sessions_score_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mock_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mock_sessions'))
    )
    op.create_index(op.f('ix_mock_sessions_user_id'), 'mock_sessions', ['user_id'], unique=False)
    op.create_table('passports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pdf_ref', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_passports_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_passports')),
    sa.UniqueConstraint('user_id', 'version', name=op.f('uq_passports_user_id'))
    )
    op.create_index(op.f('ix_passports_user_id'), 'passports', ['user_id'], unique=False)
    op.create_table('pronunciation_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weak_words', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['content_items.id'], name=op.f('fk_pronunciation_attempts_item_id_content_items')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_pronunciation_attempts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pronunciation_attempts'))
    )
    op.create_index(op.f('ix_pronunciation_attempts_item_id'), 'pronunciation_attempts', ['item_id'], unique=False)
    op.create_index('ix_pronunciation_attempts_user_created', 'pronunciation_attempts', ['user_id', 'created_at'], unique=False)
    op.create_table('interview_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('rubric_version', sa.String(length=32), nullable=False),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feedback', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total >= 0 AND total <= 100', name=op.f('ck_interview_evaluations_total_range')),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], name=op.f('fk_interview_evaluations_session_id_interview_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_evaluations')),
    sa.UniqueConstraint('session_id', name=op.f('uq_interview_evaluations_session_id'))
    )
    op.create_table('interview_turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('interviewer', 'candidate', name='turn_role', native_enum=False, length=32), nullable=False),
    sa.Column('text_ja', sa.Text(), nullable=False),
    sa.Column('stt', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], name=op.f('fk_interview_turns_session_id_interview_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_turns')),
    sa.UniqueConstraint('session_id', 'seq', name=op.f('uq_interview_turns_session_id'))
    )
    op.create_index(op.f('ix_interview_turns_session_id'), 'interview_turns', ['session_id'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('mock_session_id', sa.Integer(), nullable=True),
    sa.Column('selected_index', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['quiz_items.id'], name=op.f('fk_quiz_attempts_item_id_quiz_items')),
    sa.ForeignKeyConstraint(['mock_session_id'], ['mock_sessions.id'], name=op.f('fk_quiz_attempts_mock_session_id_mock_sessions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_quiz_attempts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_attempts'))
    )
    op.create_index(op.f('ix_quiz_attempts_item_id'), 'quiz_attempts', ['item_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_user_id'), 'quiz_attempts', ['user_id'], unique=False)
    op.create_table('share_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passport_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('view_log', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['passport_id'], ['passports.id'], name=op.f('fk_share_links_passport_id_passports')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_share_links')),
    sa.UniqueConstraint('token', name=op.f('uq_share_links_token'))
    )
    op.create_index(op.f('ix_share_links_passport_id'), 'share_links', ['passport_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_share_links_passport_id'), table_name='share_links')
    op.drop_table('share_links')
    op.drop_index(op.f('ix_quiz_attempts_user_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_item_id'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_interview_turns_session_id'), table_name='interview_turns')
    op.drop_table('interview_turns')
    op.drop_table('interview_evaluations')
    op.drop_index('ix_pronunciation_attempts_user_created', table_name='pronunciation_attempts')
    op.drop_index(op.f('ix_pronunciation_attempts_item_id'), table_name='pronunciation_attempts')
    op.drop_table('pronunciation_attempts')
    op.drop_index(op.f('ix_passports_user_id'), table_name='passports')
    op.drop_table('passports')
    op.drop_index(op.f('ix_mock_sessions_user_id'), table_name='mock_sessions')
    op.drop_table('mock_sessions')
    op.drop_index(op.f('ix_interview_sessions_user_id'), table_name='interview_sessions')
    op.drop_table('interview_sessions')
    op.drop_index('ix_events_user_created', table_name='events')
    op.drop_index(op.f('ix_events_type'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_enrollments_user_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_cohort_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_conversation_sessions_user_id'), table_name='conversation_sessions')
    op.drop_table('conversation_sessions')
    op.drop_index(op.f('ix_attitude_reviews_user_id'), table_name='attitude_reviews')
    op.drop_table('attitude_reviews')
    op.drop_index(op.f('ix_attendance_records_user_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_cohorts_org_id'), table_name='cohorts')
    op.drop_table('cohorts')
    op.drop_index(op.f('ix_quiz_items_section'), table_name='quiz_items')
    op.drop_table('quiz_items')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_content_items_sector'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_module'), table_name='content_items')
    op.drop_table('content_items')
    # ### end Alembic commands ###
